# Generated by Django 4.2.13 on 2024-06-06 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('a_ccount', '0002_alter_prof_options_prof_phone_alter_prof_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
