# Generated by Django 4.2.7 on 2024-03-17 13:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bgt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='بدون نام', max_length=25)),
                ('company', models.CharField(default='بدون شرکت', max_length=25)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.PositiveSmallIntegerField(default=0)),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('date', django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 17))),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drugs')),
                ('bgt_bill', models.PositiveSmallIntegerField(default=0)),
                ('unique', models.CharField(blank=True, max_length=100, unique=True)),
                ('currency', models.CharField(default='AFS', max_length=3)),
                ('sld_amount', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('baqi_amount', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('total', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='بدون نام', max_length=25)),
                ('company', models.CharField(max_length=25)),
                ('existing_amount', models.PositiveSmallIntegerField(default=0)),
                ('photo', models.ImageField(default='static\\UsedPhoto\\BedonAks.jpg', null=True, upload_to='')),
                ('description', models.TextField(blank=True, default='بدون جزئیات')),
                ('unique', models.CharField(blank=True, default='no name and company', max_length=60, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Sld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='بدون نام', max_length=30)),
                ('amount', models.PositiveSmallIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('date', django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 17))),
                ('company', models.CharField(default='بدون شرکت', max_length=30)),
                ('customer', models.CharField(default='نا مشخص', max_length=30)),
                ('profite', models.IntegerField(blank=True)),
                ('sld_bill', models.IntegerField(default=0)),
                ('currency', models.CharField(blank=True, default='AFS', max_length=3)),
                ('unique', models.CharField(blank=True, max_length=100, unique=True)),
                ('total', models.IntegerField(default=0)),
                ('bgt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slds', to='main.bgt')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slds', to='main.drug')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['-created'], name='main_drug_created_44f575_idx'),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['name'], name='main_drug_name_bffea9_idx'),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['company'], name='main_drug_company_f91d44_idx'),
        ),
        migrations.AddField(
            model_name='bgt',
            name='drug',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bgts', to='main.drug'),
        ),
        migrations.AddIndex(
            model_name='sld',
            index=models.Index(fields=['name'], name='main_sld_name_34b3e6_idx'),
        ),
        migrations.AddIndex(
            model_name='sld',
            index=models.Index(fields=['-date'], name='main_sld_date_344907_idx'),
        ),
        migrations.AddIndex(
            model_name='bgt',
            index=models.Index(fields=['name'], name='main_bgt_name_ee65a3_idx'),
        ),
        migrations.AddIndex(
            model_name='bgt',
            index=models.Index(fields=['company'], name='main_bgt_company_32752e_idx'),
        ),
        migrations.AddIndex(
            model_name='bgt',
            index=models.Index(fields=['-date'], name='main_bgt_date_f0244d_idx'),
        ),
    ]
