# Generated by Django 4.2.7 on 2024-03-15 03:18

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgt',
            name='unique',
        ),
        migrations.RemoveField(
            model_name='sld',
            name='unique',
        ),
        migrations.AddField(
            model_name='bgt',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='sld',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='bgt',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 15)),
        ),
        migrations.AlterField(
            model_name='sld',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 15)),
        ),
    ]
