# Generated by Django 4.2.7 on 2024-02-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='unique',
            field=models.CharField(blank=True, default='no name and company', max_length=60, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sld',
            name='currency',
            field=models.CharField(blank=True, default='AFS', max_length=3),
        ),
    ]
