# Generated by Django 4.2.13 on 2024-06-06 14:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_bgt_amount_alter_bgt_baqi_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgt',
            name='Buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sld',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bgt',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 6, 6)),
        ),
        migrations.AlterField(
            model_name='sld',
            name='bgt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='main.bgt'),
        ),
        migrations.AlterField(
            model_name='sld',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 6, 6)),
        ),
    ]
