# Generated by Django 4.2.7 on 2024-03-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_bgt_unique_remove_sld_unique_bgt_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgt',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='sld',
            name='slug',
        ),
        migrations.AddField(
            model_name='bgt',
            name='unique',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='sld',
            name='unique',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
