# Generated by Django 4.2.7 on 2024-02-23 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_drug_unique_alter_sld_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='sld',
            name='bgt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slds', to='main.bgt'),
        ),
    ]
