# Generated by Django 4.2.7 on 2024-02-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bgt_photo_alter_drug_existing_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bgt',
            old_name='price',
            new_name='bg_price',
        ),
    ]
