# Generated by Django 4.2.7 on 2024-03-06 01:57

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_drug_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bgt',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sld',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='bgt',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 6)),
        ),
        migrations.AlterField(
            model_name='sld',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 6)),
        ),
    ]
