# Generated by Django 4.2.7 on 2024-03-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bgt_options_alter_drug_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='unique',
            field=models.CharField(blank=True, default='no name and company', max_length=60, primary_key=True, serialize=False),
        ),
    ]
