# Generated by Django 4.2.13 on 2024-06-06 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bgt_buyer_sld_seller_alter_bgt_date_alter_sld_bgt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bgt',
            options={'ordering': ['-name'], 'verbose_name': 'Purchase'},
        ),
        migrations.AlterModelOptions(
            name='sld',
            options={'ordering': ['-date'], 'verbose_name': 'Sale'},
        ),
        migrations.AlterField(
            model_name='bgt',
            name='bgt_bill',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='bill'),
        ),
        migrations.AlterField(
            model_name='bgt',
            name='drug',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Purchases', to='main.drug'),
        ),
        migrations.AlterField(
            model_name='sld',
            name='bgt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='main.bgt', verbose_name='Purchase'),
        ),
        migrations.AlterField(
            model_name='sld',
            name='sld_bill',
            field=models.IntegerField(default=0, verbose_name='bill'),
        ),
    ]
