# Generated by Django 4.2.7 on 2024-02-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_price_bgt_bg_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgt',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drugs'),
        ),
    ]
