# Generated by Django 4.2.7 on 2024-02-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_bgt_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgt',
            name='currency',
            field=models.CharField(default='AFS', max_length=3),
        ),
        migrations.AlterField(
            model_name='drug',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
