# Generated by Django 4.2.7 on 2024-03-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_drug_unique'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bgt',
            index=models.Index(fields=['-date'], name='main_bgt_date_f0244d_idx'),
        ),
        migrations.AddIndex(
            model_name='sld',
            index=models.Index(fields=['-date'], name='main_sld_date_344907_idx'),
        ),
    ]
