# Generated by Django 4.2.7 on 2024-02-25 09:02

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_bgt_bg_date_alter_bgt_date_alter_sld_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgt',
            name='bg_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 2, 25)),
        ),
        migrations.AlterField(
            model_name='sld',
            name='sld_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 2, 25)),
        ),
    ]
