# Generated by Django 5.0.6 on 2024-06-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bill_alter_bgt_date_alter_sld_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillBgt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.BooleanField(default=False)),
                ('date', models.CharField(max_length=60)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Bill',
            new_name='BillSld',
        ),
    ]
