# Generated by Django 4.2.7 on 2024-02-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_bgt_currency_alter_drug_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgt',
            name='currency',
            field=models.CharField(blank=True, default='AFS', max_length=3),
        ),
    ]
