# Generated by Django 4.2.7 on 2024-03-06 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bgt_main_bgt_date_f0244d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgt',
            name='drug',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bgts', to='main.drug'),
        ),
        migrations.AlterField(
            model_name='bgt',
            name='photo',
            field=models.ImageField(blank=True, default='static\\UsedPhoto\\BedonAks.jpg', null=True, upload_to='drugs'),
        ),
    ]
