# Generated by Django 5.0.6 on 2024-06-14 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_billbgt_rename_bill_billsld'),
    ]

    operations = [
        migrations.AddField(
            model_name='sld',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='slds', to='main.billsld'),
        ),
    ]
