# Generated by Django 4.2.7 on 2024-02-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_bgt_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgt',
            name='currency',
            field=models.CharField(default='AFS', max_length=3),
        ),
    ]
