# Generated by Django 5.0.6 on 2024-06-14 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_bill_sld_bill_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sld',
            name='bill_object',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='slds', to='main.billsld'),
        ),
    ]
