# Generated by Django 5.0.6 on 2024-06-15 23:55

import datetime
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_sld_bill_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgt',
            name='bill_object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bgts', to='main.billbgt'),
        ),
        migrations.AlterField(
            model_name='bgt',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 6, 15)),
        ),
        migrations.AlterField(
            model_name='sld',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 6, 15)),
        ),
    ]
