# Generated by Django 5.0.6 on 2024-06-16 00:01

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_bgt_bill_object_alter_bgt_date_alter_sld_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billbgt',
            name='company',
            field=models.CharField(default='default-company', max_length=60),
        ),
        migrations.AlterField(
            model_name='bgt',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 6, 16)),
        ),
        migrations.AlterField(
            model_name='sld',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 6, 16)),
        ),
    ]
