# Generated by Django 5.0.6 on 2024-06-16 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_billbgt_company_alter_bgt_date_alter_sld_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgt',
            name='bill_object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bgts', to='main.billbgt'),
        ),
        migrations.AlterField(
            model_name='sld',
            name='bill_object',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='slds', to='main.billsld'),
        ),
    ]
